#ifndef cbindgen_bindings_h
#define cbindgen_bindings_h

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stdlib.h>
#include <stdbool.h>

char *say_hello(void);

#endif /* cbindgen_bindings_h */
